# group_imports       = "StdExternalCrate"
# imports_granularity = "Crate"
reorder_imports      = true
use_small_heuristics = "Max"

# normalize_comments = true
# wrap_comments      = true

# condense_wildcard_suffixes   = true
# enum_discrim_align_threshold = 20
# reorder_impl_items           = true
use_field_init_shorthand = true

# format_code_in_doc_comments = true
# format_macro_matchers       = true
# format_strings              = true
