[package]
authors     = ["magic-akari <akari.ccino@gmail.com>"]
description = "A WASM Based SQL Formatter"
name        = "sql_fmt"

edition    = "2024"
homepage   = "https://github.com/wasm-fmt/sql_fmt"
keywords   = ["wasm", "sql", "formatter"]
license    = "MIT OR Apache-2.0"
readme     = "README.md"
repository = "https://github.com/wasm-fmt/sql_fmt"
version    = "0.2.2"

[dependencies]
bridge     = { package = "wasm-fmt-fdk", version = "=0.1.0" }
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlformat  = "0.5.0"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
debug         = false     # set to `true` for debug information
lto           = true
opt-level     = 2
panic         = "abort"   # Let it crash and force ourselves to write safe Rust.
strip         = "symbols" # set to `false` for debug information
