name: Publish

on:
  push:
    tags:
      - "v*"

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: "always"
  RUST_LOG: "off"

jobs:
  wasm-build:
    name: Wasm build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build wasm
        run: ./scripts/build.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: pkg

  publish-npm:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: wasm-build
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: pkg

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"

      - name: Publish
        working-directory: pkg
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: wasm-build
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: pkg

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          registry-url: "https://npm.pkg.github.com"

      - name: Publish
        working-directory: pkg
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-jsr:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: wasm-build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: pkg

      - run: npx jsr publish
        working-directory: pkg/

  publish-github-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: wasm-build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: pkg

      - name: Package
        working-directory: pkg
        run: npm pack

      - name: Release
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        with:
          files: |
            pkg/*.tgz
            pkg/*.wasm
